relay_host: "127.0.0.1"
relay_port_client: 8081
rsa_private_key: "certs/client_private.pem"
rsa_public_key: "certs/relay_public.pem"
auth_key: ""
agents:
  - agent_id: "agent-a"
    services:
      directed:
        - id: "rule1"
          local_port: 3005
          target_url: "http://target1.cn:80"
          enabled: true
      general:
        local_port: 3000
        bind: "127.0.0.1"
        enabled: true
      shell:
        local_port: 3001
        enabled: true
  - agent_id: "agent-b"
    services:
      directed: []
      general:
        local_port: 3010
        bind: "127.0.0.1"
        enabled: false
      shell:
        local_port: 3001
        enabled: true
heartbeat_interval: 25
control_dead_timeout: 120
pool_dead_timeout: 120
client_self_check_pool_probe_timeout: 5.0
log_level: "info"

